# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: git Actions
      uses: srt32/git-actions@v0.0.3
    - name: Preparing Libs directory
      run: mkdir libs
    - name: Download PolarCore Releases.
      uses: Legion2/download-release-action@v2.1.0
      with:
        repository: saltedfishclub/PolarCore
        tag: 'v1.1'
        path: libs
        file: Core-1.1-SNAPSHOT-all.jar
    - name: Check
      run: ls libs
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew shadowjar
    - name: Rename Artifact
      run: mv ./build/libs/*.jar ./build/libs/MiraiWrapper.jar
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: MiraiWrapper.jar
        path: build/libs
